swagger: "2.0"
info:
  version: "1.0"
  title: "Kong Adapter OAuth 2.0 Implicit Flow Registration API"
basePath: "/oauth2"
consumes:
  - application/json
schemes:
  - http
paths:
  /register:
    post:
      parameters:
        - name: user
          in: body
          schema:
            $ref: '#/definitions/implicitRegistrationType'
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/implicitSuccessType'
        401:
          description: Unauthorized
        404:
          description: Not found

definitions:
  implicitRegistrationType:
    type: object
    properties:
#      email:
#        type: string
      authenticated_userid:
        type: string
      api_id:
        type: string
      client_id:
        type: string
      scope:
        type: array
        items:
          type: string
#      headers:
#        type: array
#        items:
#          type: object
#          additionalProperties:
#            type: string
  implicitSuccessType:
    type: object
    properties:
      redirect_uri:
        type: string
